#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinNativeFacebook.Droid.Resource", IsApplication=true)]

namespace XamarinNativeFacebook.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010015
			public const int auxiliary_view_position = 2130771989;
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010012
			public const int foreground_color = 2130771986;
			
			// aapt resource value: 0x7f010016
			public const int horizontal_alignment = 2130771990;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010013
			public const int object_id = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int style = 2130771988;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_blue = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_likeboxcountview_border_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeboxcountview_text_color = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_likebutton_text_color = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_likeview_text_color = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_text_color = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_picker_search_bar_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_picker_search_bar_text = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040015
			public const int com_facebook_likeboxcountview_border_radius = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int com_facebook_likeboxcountview_border_width = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int com_facebook_likeboxcountview_caret_height = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int com_facebook_likeboxcountview_caret_width = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int com_facebook_likeboxcountview_text_padding = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int com_facebook_likeboxcountview_text_size = 2130968599;
			
			// aapt resource value: 0x7f040011
			public const int com_facebook_likebutton_compound_drawable_padding = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int com_facebook_likebutton_padding_bottom = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_likebutton_padding_left = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_likebutton_padding_right = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_likebutton_padding_top = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int com_facebook_likebutton_text_size = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_likeview_edge_padding = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_likeview_internal_padding = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_likeview_text_size = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loginview_compound_drawable_padding = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_loginview_padding_bottom = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_loginview_padding_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_loginview_padding_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_loginview_padding_top = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_text_size = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_picker_divider_width = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_picker_place_image_size = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int com_facebook_profilepictureview_preset_size_large = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int com_facebook_profilepictureview_preset_size_normal = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int com_facebook_profilepictureview_preset_size_small = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int com_facebook_tooltip_horizontal_padding = 2130968604;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_blue_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_blue_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_blue_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_check_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_check_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_grey_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_grey_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_grey_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_like = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_like_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_like_background_selected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_button_like_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_button_like_icon_selected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_like_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_like_selected = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_close = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_inverse_icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_list_divider = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_list_section_header_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_loginbutton_silver = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_logo = 2130837526;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_picker_default_separator_color = 2130837553;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_picker_item_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_picker_list_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_picker_list_longpressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_picker_list_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_picker_list_selector = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_picker_list_selector_background_transition = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_picker_list_selector_disabled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_picker_magnifier = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_picker_top_button = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_place_default_icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_profile_default_icon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_profile_picture_blank_portrait = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_profile_picture_blank_square = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_tooltip_black_background = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_tooltip_black_bottomnub = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_tooltip_black_topnub = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_tooltip_black_xout = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_tooltip_blue_background = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_tooltip_blue_bottomnub = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_tooltip_blue_topnub = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_tooltip_blue_xout = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_top_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_top_button = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int monoandroidsplash = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int bottom = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int box_count = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int button = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int center = 2131230729;
			
			// aapt resource value: 0x7f08001e
			public const int com_facebook_body_frame = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int com_facebook_button_xout = 2131230752;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_login_activity_progress_bar = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int com_facebook_picker_activity_circle = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_picker_checkbox = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int com_facebook_picker_checkbox_stub = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_picker_divider = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_picker_done_button = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_picker_image = 2131230737;
			
			// aapt resource value: 0x7f080015
			public const int com_facebook_picker_list_section_header = 2131230741;
			
			// aapt resource value: 0x7f08000c
			public const int com_facebook_picker_list_view = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_picker_profile_pic_stub = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_picker_row_activity_circle = 2131230735;
			
			// aapt resource value: 0x7f08001d
			public const int com_facebook_picker_search_text = 2131230749;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_picker_title = 2131230739;
			
			// aapt resource value: 0x7f08001a
			public const int com_facebook_picker_title_bar = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int com_facebook_picker_title_bar_stub = 2131230745;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_picker_top_bar = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int com_facebook_search_bar_view = 2131230748;
			
			// aapt resource value: 0x7f080022
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int com_facebook_tooltip_bubble_view_text_body = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131230751;
			
			// aapt resource value: 0x7f080025
			public const int com_facebook_usersettingsfragment_login_button = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int com_facebook_usersettingsfragment_logo_image = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int com_facebook_usersettingsfragment_profile_name = 2131230756;
			
			// aapt resource value: 0x7f080007
			public const int inline = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int large = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int left = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int normal = 2131230721;
			
			// aapt resource value: 0x7f08001b
			public const int picker_subtitle = 2131230747;
			
			// aapt resource value: 0x7f08000b
			public const int right = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int small = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int standard = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int top = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_friendpickerfragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_activity_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_picker_activity_circle_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_checkbox = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_image = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_list_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_section_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_search_box = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_title_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar_stub = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_placepickerfragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment_list_row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_search_bar_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_tooltip_bubble = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_usersettingsfragment = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001d
			public const int app_id = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int app_name = 2131099678;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_choose_friends = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_dialogloginactivity_ok_button = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int com_facebook_image_download_unknown_error = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_internet_permission_error_message = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_internet_permission_error_title = 2131099668;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_like_button_liked = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_like_button_not_liked = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_loading = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_loginview_cancel_action = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_loginview_log_in_button = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_loginview_log_out_action = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_loginview_log_out_button = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_loginview_logged_in_as = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_logged_in_using_facebook = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_logo_content_description = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_nearby = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_picker_done_button_text = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_placepicker_subtitle_format = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_requesterror_password_changed = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int com_facebook_requesterror_permissions = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int com_facebook_requesterror_reconnect = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_requesterror_relogin = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_requesterror_web_login = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int com_facebook_tooltip_default = 2131099675;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_usersettingsfragment_log_in_button = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_usersettingsfragment_logged_in = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int Mono_Android_Theme_Splash = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int Theme_MainBackground = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_loginview_default_style = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_loginview_silver_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int tooltip_bubble_text = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 3
			public const int com_facebook_like_view_auxiliary_view_position = 3;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_foreground_color = 0;
			
			// aapt resource value: 4
			public const int com_facebook_like_view_horizontal_alignment = 4;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_style = 2;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
